import { promises as fs } from "node:fs";
import path from "node:path";
import { prisma } from "../lib/prisma.js";
import { env } from "../config/env.js";
import { decrypt } from "../lib/crypto.js";
import { appendLog, updateDeploymentStatus } from "../services/deployment.service.js";
import { dequeueDeployJob } from "../lib/queue.js";
import {
  allocatePort,
  containerName,
  docker,
  git,
  imageName,
  isDockerAvailable,
  stopAndRemoveContainer,
} from "./docker.js";

let running = false;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function serviceWorkspace(serviceId: string): string {
  return path.join(env.WORKSPACE_DIR, serviceId);
}

function deployUrl(slug: string, hostPort: number): string {
  if (env.DEPLOY_DOMAIN) return `https://${slug}.${env.DEPLOY_DOMAIN}`;
  return `http://${env.DEPLOY_PUBLIC_HOST}:${hostPort}`;
}

async function isCancelled(deploymentId: string): Promise<boolean> {
  const d = await prisma.deployment.findUnique({
    where: { id: deploymentId },
    select: { status: true },
  });
  return d?.status === "CANCELLED";
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

// Builds the authenticated (or plain) clone URL for a GitHub repository.
function cloneUrl(repoFullName: string): string {
  const token = process.env.GIT_CLONE_TOKEN;
  if (token) return `https://x-access-token:${token}@github.com/${repoFullName}.git`;
  return `https://github.com/${repoFullName}.git`;
}

// Writes a generic Dockerfile when the repository does not ship one. The app is
// expected to listen on $PORT (injected as DEPLOY_CONTAINER_PORT).
async function ensureDockerfile(
  workdir: string,
  buildCommand: string,
  startCommand: string,
): Promise<boolean> {
  const repoDockerfile = path.join(workdir, "Dockerfile");
  if (await pathExists(repoDockerfile)) return false; // use the repo's own Dockerfile

  const port = env.DEPLOY_CONTAINER_PORT;
  const dockerfile = `# Auto-generated by Stella Hosting runner
FROM ${env.DEPLOY_BASE_IMAGE}
WORKDIR /app
ENV PORT=${port}
ENV NODE_ENV=production
COPY . .
RUN sh -c ${JSON.stringify(buildCommand)}
EXPOSE ${port}
CMD ["sh", "-c", ${JSON.stringify(startCommand)}]
`;
  await fs.writeFile(path.join(workdir, ".stella.Dockerfile"), dockerfile, "utf8");
  return true;
}

// ---------------------------------------------------------------------------
// Deployment pipeline
// ---------------------------------------------------------------------------

export async function runDeployment(deploymentId: string): Promise<void> {
  const deployment = await prisma.deployment.findUnique({
    where: { id: deploymentId },
    include: { service: { include: { envVars: true } } },
  });
  if (!deployment) return;
  const { service } = deployment;
  const userId = deployment.userId;

  const log = (message: string, stream: "STDOUT" | "STDERR" | "SYSTEM" = "SYSTEM") =>
    appendLog({
      deploymentId,
      userId,
      message,
      stream,
      level: stream === "STDERR" ? "WARN" : "INFO",
    });

  try {
    if (await isCancelled(deploymentId)) return;

    await updateDeploymentStatus({ deploymentId, userId, status: "BUILDING" });

    // 1. Checkout -----------------------------------------------------------
    const workdir = serviceWorkspace(service.id);
    await fs.mkdir(env.WORKSPACE_DIR, { recursive: true });

    const branch = deployment.branch || service.branch || "main";
    const onLine = (line: string, stream: "STDOUT" | "STDERR") => log(line, stream);

    if (await pathExists(path.join(workdir, ".git"))) {
      await log(`Fetching latest changes for ${service.repoFullName}#${branch}…`);
      await git(["-C", workdir, "remote", "set-url", "origin", cloneUrl(service.repoFullName)]);
      const fetched = await git(["-C", workdir, "fetch", "origin", branch, "--depth", "1"], {
        onLine,
        timeoutMs: 5 * 60_000,
      });
      if (fetched.code !== 0) throw new Error("git fetch failed");
      await git(["-C", workdir, "checkout", "-f", branch], { onLine });
      await git(["-C", workdir, "reset", "--hard", `origin/${branch}`], { onLine });
    } else {
      await fs.rm(workdir, { recursive: true, force: true });
      await log(`Cloning ${service.repoFullName}#${branch}…`);
      const cloned = await git(
        ["clone", "--depth", "1", "--branch", branch, cloneUrl(service.repoFullName), workdir],
        { onLine, timeoutMs: 5 * 60_000 },
      );
      if (cloned.code !== 0) throw new Error("git clone failed");
    }

    // Optionally check out a specific commit for reproducible deploys.
    if (deployment.commitSha) {
      await git(["-C", workdir, "checkout", "-f", deployment.commitSha], { onLine }).catch(
        () => undefined,
      );
    }

    // Record the resolved commit metadata.
    const rev = await git(["-C", workdir, "rev-parse", "HEAD"]);
    const sha = rev.stdout.trim().slice(0, 40);
    if (sha) {
      await prisma.deployment.update({
        where: { id: deploymentId },
        data: { commitSha: deployment.commitSha ?? sha },
      });
    }

    if (await isCancelled(deploymentId)) {
      await log("Deployment cancelled before build.");
      return;
    }

    // 2. Build --------------------------------------------------------------
    await log("Building container image…");
    const usedGenerated = await ensureDockerfile(workdir, service.buildCommand, service.startCommand);
    const dockerfileArgs = usedGenerated ? ["-f", path.join(workdir, ".stella.Dockerfile")] : [];

    const img = imageName(service.id);
    const build = await docker(
      ["build", "--pull", "-t", img, ...dockerfileArgs, workdir],
      { onLine, timeoutMs: 20 * 60_000 },
    );
    if (build.code !== 0) throw new Error("Image build failed");

    if (await isCancelled(deploymentId)) {
      await log("Deployment cancelled before release.");
      return;
    }

    // 3. Release ------------------------------------------------------------
    await updateDeploymentStatus({ deploymentId, userId, status: "DEPLOYING" });
    await log("Stopping previous container (if any)…");
    await stopAndRemoveContainer(service.id);

    const hostPort = await allocatePort(service.id);
    const decryptedEnv = service.envVars.flatMap((e) => {
      try {
        return ["-e", `${e.key}=${decrypt(e.value)}`];
      } catch {
        return [];
      }
    });

    await log(`Starting container on host port ${hostPort}…`);
    const run = await docker(
      [
        "run",
        "-d",
        "--name",
        containerName(service.id),
        "--restart",
        "unless-stopped",
        "--cpus",
        env.DEPLOY_CPU_LIMIT,
        "--memory",
        env.DEPLOY_MEMORY_LIMIT,
        "--pids-limit",
        "256",
        "--security-opt",
        "no-new-privileges",
        "-e",
        `PORT=${env.DEPLOY_CONTAINER_PORT}`,
        ...decryptedEnv,
        "-p",
        `${hostPort}:${env.DEPLOY_CONTAINER_PORT}`,
        "--label",
        "stella.managed=true",
        "--label",
        `stella.service=${service.id}`,
        img,
      ],
      { onLine },
    );
    if (run.code !== 0) throw new Error("Container failed to start");

    // 4. Health check -------------------------------------------------------
    await log("Running health check…");
    const healthy = await waitForHealthy(hostPort);
    if (!healthy) {
      // Capture the last container logs to help debugging.
      await docker(["logs", "--tail", "40", containerName(service.id)], { onLine }).catch(
        () => undefined,
      );
      throw new Error("Health check failed — container did not become reachable");
    }

    const url = deployUrl(service.slug, hostPort);
    await log(`Deployment live at ${url} 🚀`);
    await updateDeploymentStatus({ deploymentId, userId, status: "LIVE", url });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    await appendLog({
      deploymentId,
      userId,
      message: `Deployment failed: ${message}`,
      stream: "SYSTEM",
      level: "ERROR",
    }).catch(() => undefined);
    await updateDeploymentStatus({ deploymentId, userId, status: "FAILED" }).catch(
      () => undefined,
    );
  }
}

// Polls the container's mapped port until it responds or the deadline passes.
async function waitForHealthy(hostPort: number, deadlineMs = 60_000): Promise<boolean> {
  const url = `http://127.0.0.1:${hostPort}/`;
  const start = Date.now();
  while (Date.now() - start < deadlineMs) {
    try {
      const res = await fetch(url, { method: "GET", signal: AbortSignal.timeout(4000) });
      // Any HTTP response (even 4xx/5xx) means the process is up and listening.
      if (res.status >= 100) return true;
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, 2000));
  }
  return false;
}

// ---------------------------------------------------------------------------
// Worker loop
// ---------------------------------------------------------------------------

export async function startRunner(): Promise<void> {
  if (running) return;
  running = true;

  const dockerOk = await isDockerAvailable();
  if (!dockerOk) {
    console.warn(
      "[runner] Docker is not available — deployment builds are disabled on this node. " +
        "Install Docker and mount /var/run/docker.sock to enable the runner.",
    );
    return;
  }

  console.log("🛠️  Deployment runner started (Docker-based builds enabled)");

  void (async () => {
    while (running) {
      try {
        const job = await dequeueDeployJob(5);
        if (!job) continue;
        await runDeployment(job.deploymentId);
      } catch (err) {
        console.error("[runner] loop error", err);
        await new Promise((r) => setTimeout(r, 1000));
      }
    }
  })();
}

export function stopRunner() {
  running = false;
}
